name: EXP-WorldGuard
version: ${version}
main: co.killionrevival.expworldguard.ExpWorldGuard
api-version: ${mcVersion}
description: A plugin that add a WorldGuard tag for only letting players in an area if they have a certain EXP level.
dependencies:
  server:
    KillionCommons:
      load: BEFORE
    WorldGuard:
      load: BEFORE
authors: [flyerzrule] 
permissions:
  expworldguard.bypass:
    description: Bypasses the EXP requirement.
    default: op